name: K6 Performance Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup K6
        uses: grafana/setup-k6-action@v1.1.0

      - name: Run K6 test
        run: |
          mkdir -p src/output
          k6 run src/tests/main.test.js
